lib/get-repo-id.js
lib/publish.js
lib/verify.js
package.json
test/get-repo-id.test.js
test/verify.test.js

Extract the repository id from the repository URL as follow:
- `htttp://gitlab.com/owner/repo.git` => `owner%2Frepo`
- `htttp://gitlab.com/orga/owner/repo.git` => `orga%2Fowner%2Frepo`
- `htttp://gitlab.com/orga/group/owner/repo.git` => `orga%2Fgroup%2Fowner%2Frepo`
- `htttp://custom.com/context/orga/group/owner/repo.git` => `orga%2Fgroup%2Fowner%2Frepo` (if gitlab URL is `htttp://custom.com/context`)
Also works with `git` and `git+ssh` URLs.
Fix #2

fix: support repositories within subgroups

---

lib/publish.js
lib/resolve-config.js
lib/verify.js
package.json
test/helpers/mock-gitlab.js
test/integration.test.js
test/publish.test.js
test/verify.test.js

BREAKING CHANGE: require `semantic-release` >= `15.8.0`

feat: use `cwd` and `env` options passed by core

---

lib/publish.js
test/publish.test.js

BREAKING CHANGE: require GitLab version >= `11.7`
Fix #79

feat: add asset links to release using api and remove them from markdown

---

README.md
lib/glob-assets.js
test/glob-assets.test.js

Fixes https://github.com/semantic-release/gitlab/issues/158 by using the correct property name (`label`) that is used as the link name in the GitLab release.
Given a configuration like this:
```json
{
"plugins": [
[
"@semantic-release/gitlab",
{
"assets": [
{ "path": "src/**/*", "label": "Source files" },
{ "path": "build/**/*", "label": "Compiled files" }
]
}
]
]
}
```
**Before:**
When a glob pattern matched multiple files (just `build/**/*` in this example), each matched file was uploaded with the provided name ("Compiled files"), causing a validation error for every file but the first. 
**After:**
When a glob pattern matches multiple files, each matched file is uploaded with its file name instead of the provided `label`.
---
Closes https://github.com/semantic-release/gitlab/issues/158

fix(publish): use file name as label when multiple

---

lib/publish.js
test/integration.test.js
test/publish.test.js

Resolves #183 by updating all requests to:
```
https://example.gitlab.com/api/v4/project/<project id>/repository/tags<tag name>/release`
```
to instead call:
```
https://example.gitlab.com/api/v4/project/<project id>/releases`
```
The former is deprecated and will be removed in GitLab 14.0 (in May 2021); see https://gitlab.com/gitlab-org/gitlab/-/issues/290311.
This has the added benefit of simplifying the process of uploading assets. The Releases API allows a release to be created with assets in a single request, removing the need to create assets separately.
This change is backwards compatible (the Releases API has been available since GitLab 11.7 - when the releases feature itself was delivered) and shouldn't impact current users of this plugin.
I've tested this change in a test …

refactor: replace deprecated Tags API call

---

lib/publish.js
test/integration.test.js
test/publish.test.js

I noticed this while putting together https://github.com/semantic-release/gitlab/pull/184 and thought I'd open a separate issue to discuss.
Updates the return value of `publish.js` to return a web URL to the _release_ instead of the _tag_. This is more consistent with `semantic-release/github`: https://github.com/semantic-release/github/blob/81847f1abd1c9714e28a17f712739ffebb586bec/lib/publish.js#L101
Here's an example of what a "tag" page looks like: https://gitlab.com/gitlab-org/gitlab/-/tags/v13.6.0-ee
And here's an example of its corresponding "release" page: https://gitlab.com/gitlab-org/gitlab/-/releases/v13.6.0-ee
The later is a nicer representation of the release, and we may be removing release notes from the former in the future: …

fix: update release URL returned from publish.js

---

lib/verify.js

Currently, the error handling in `verify.js` assumes the error object will always contain a `response` property. This isn't always true; for example, SSL errors will throw an error object without a `response`.
This MR updates the error handling to check for `response` before accessing `response.statusCode`. If `response` doesn't exist, the error is re-thrown.
Related to https://github.com/semantic-release/gitlab/issues/186 and https://github.com/semantic-release/gitlab/issues/212

fix: handle errors that don't have a `response`

---

README.md
lib/publish.js
lib/resolve-config.js
test/publish.test.js
test/resolve-config.test.js

Adds support to attach milestones to the created GitLab Release via the plugin configuration
See: https://docs.gitlab.com/ee/api/releases/#create-a-release

feat: support gitlab milestones in config

---

README.md
lib/glob-assets.js
lib/publish.js
test/glob-assets.test.js
test/publish.test.js

Implemented two options for assets according to GitLab [document on asset permanent link and link type](https://git.bdaa.pro/help/user/project/releases/index#permanent-links-to-release-assets), addressing #161.
It can also be a solution to #167, with which now we can download asset using URL like this: `https://host/namespace/project/releases/v1.0.0/downloads/build.tar.gz`

feat: support asset type and filepath

---

lib/publish.js

Adds some additional logging to `publish.js`, including error logs when requests to GitLab's API fail.
Currently, if a request to GitLab's API fails, this plugin logs a generic error message without any specifics. This makes it hard for end-users to diagnose and fix issues.

fix: better error logging for network errors

---

README.md

Adds a note about which versions of GitLab are supported by this plugin, and also adds a note about a specific breaking change in GitLab 14.0.

docs: add note about version compatibility

---

lib/definitions/errors.js

fix(error-message): spelling of personal

---

README.md
index.js
lib/definitions/constants.js
lib/get-success-comment.js
lib/publish.js
lib/resolve-config.js
lib/success.js
test/publish.test.js
test/resolve-config.test.js
test/success.test.js

BREAKING CHANGE: By default all related issues and MRs are commented. Set the `successComment` option to `false` to disable that.
Fixes #40
🛠 with ❤ at [Siemens](https://opensource.siemens.io)

feat: comment on issues and merge requests resolved by current release

---

lib/get-success-comment.js
lib/publish.js
test/integration.test.js
test/publish.test.js
test/success.test.js

First of all thanks to @fgreinacher for this nice feature.
We are using it already and I stumpled upon two issues:
- the :package: and :rocket: icon were not proberly displayed as they were not separated
- the URL to the release did not work because of `%2F` in the URI; this is why I added the `decodeURIComponent`
Fixes #344

fix: display default icons and fix URL in success message

---

README.md
index.js
lib/definitions/constants.js
lib/definitions/errors.js
lib/fail.js
lib/get-fail-comment.js
lib/get-success-comment.js
lib/resolve-config.js
lib/verify.js
test/fail.test.js
test/resolve-config.test.js
test/verify.test.js

- adapted from [github](https://github.com/semantic-release/github)

feat: create issues when the release is failing

---

README.md
lib/resolve-config.js
package-lock.json
package.json
test/resolve-config.test.js

- Add NO_PROXY environment variable support
- NO_PROXY environment variables is completely ignored
- NO_PROXY environment variables can be used to bypass the proxy configuration via HTTPS_PROXY and/or HTTP_PROXY envrionment variables
No
In some cases it requires a web proxy to reach resources through the internet and outside of a company network. This will work when the gitlab Instance is also accessible through the internet, but in some cases the gitlab instance is a self hosted one and is only be reachable within the same network.
In case of that you need a proxy configuration (e.g. through HTTP_PROXY and/or HTTPS_PROXY for your build process with @semantic-release/exec) it would fail to reach the gitlab instance as a combination of proxy and no_proxy is not possible at the moment.
This …

feat: add support for NO_PROXY

---

lib/verify.js
test/verify.test.js

fix(verify): gracefully handle options without validator

---

README.md
lib/publish.js
test/publish.test.js

As mentioned in #334 it could be useful to use templating for the asset labels. This PR provides the functionality to use the lodash templating functionality similar to the `successComment` and the `failComment`.
Resolves #334

feat(assets): allow label templating #334

---

README.md

Two arguments were switched around and one of the links stated they were linking to GitHub while they were (and should be) linking to GitLab.

docs: fix successComment documentation

---

README.md
lib/publish.js
test/publish.test.js

I added templating functioniality to `url`, `type` and ` filepath` like already done in #365 for `label`.
Closes #406 
Hope you like it (:

Allow templating

---

README.md
lib/definitions/errors.js
lib/verify.js
test/verify.test.js

Closes #449 
Summary
- Add check for `dryRun` in **verify** step
- Expand error codes to differentiate between repository "pull" and "push" permission errors.

feat(verify): Reduce access_level requirements when using --dry-run

---

README.md
lib/publish.js
test/publish.test.js

> Progress of #283 which I closed due to missing time on my side
Gitlab allows to add generic packages as assets attached to a release. #174 This is a suggestion to define a list of generics to be published into the generics repository of a project and then to be used as assets for the release.

feat(generics): allow upload of build assets as generic packages #174

---

package.json

It is not used anywhere in the code and is only needed during development.
Also, some people, like me, depend on a [fork of prettier](https://www.npmjs.com/package/@btmills/prettier) and now, depending on the order the dependencies get installed, either the fork or the original get used, which makes ci/cd a nightmare because builds gets unreproducible.

fix: move prettier to devDependencies

---

README.md
lib/publish.js
test/publish.test.js

This should fix #490 (WIP). Working on it I found some issues which were not recognized yet:
- wrong README example
- missing proxy
- invalid URL if `gitlapApiUrl` is set

fix(generic-package): fix issues when uploading multiple assets

---

lib/get-repo-id.js
test/get-repo-id.test.js

Before we used the project path, which can cause issues with some proxy or firewall setups that replace slashes in URLs.
Closes https://github.com/semantic-release/gitlab/issues/543

fix: use numeric project ID for API calls

---

lib/get-repo-id.js
test/get-repo-id.test.js

The numeric project ID is not working for all cases and I don't have the capacity right now to think about a generic solution.
People that have issues with the project path can override `CI_PROJECT_PATH` for the semantic-release invocation. 
Reverts semantic-release/gitlab#576
Closes #579 
/cc @JedaiRussia @gaborauth

fix: use project path for API calls again

---

.github/workflows/test.yml
lib/publish.js
package-lock.json
package.json

This bumps the minimum supported Node version to 20.8.1. Node 20 is the new LTS version and some of our dependencies already dropped supported for Node 18. Check out [our Node Support Policy](https://semantic-release.gitbook.io/semantic-release/support/node-support-policy) for how we handle Node versions.
BREAKING CHANGE: Node 18 and 19 are not supported anymore. Users have to upgrade to Node 20.8.1 or later.

chore: bump minimum Node version to 20.8.1

---

package.json

to better align with the recommendation for org-level presets: docs.renovatebot.com/config-presets/#grouporganization-level-presets

ci(renovate): fixed the reference to the org-level config

---

lib/fail.js
test/fail.test.js

I realized in our logs, the `id` and `web_url` are not parsed properly. According to the docs the call to the method `.json()` was missing. Local tests showed this fixed the logs and did not affect the normal functionality.

fix(fail): properly parse issue creation response to log in terminal

---

lib/definitions/errors.js

Neither import assertions nor the with keyword is supported across our supported versions.
Instead of going for a breaking change and raise our Node dependency I suggest we apply the same logic as [in the GitHub plugin](https://github.com/semantic-release/github/blob/master/lib/definitions/errors.js#L7).
Resolves https://github.com/semantic-release/gitlab/issues/704

fix: get rid of import assertion

---

lib/publish.js
test/publish.test.js

This PR adds the message from the response body to the error if available.
Resolves https://github.com/semantic-release/gitlab/issues/684

feat: improve output in case of errors during publish

---

lib/publish.js
test/publish.test.js

Moved from https://github.com/semantic-release/gitlab/pull/754
Fixes #753

Upload 404 fix

---

README.md

Add assets label for url otherwise release is not created because GitLab API expect a assets:links:name.
https://docs.gitlab.com/ee/api/releases/#create-a-release

fix: updated configuration example

---

lib/fail.js
lib/publish.js
lib/resolve-config.js
lib/success.js
test/resolve-config.test.js

> https://github.com/sindresorhus/got/blob/a359bd385129d2adbc765b52dfbbadac5f54a825/documentation/7-retry.md#retry
This could fix #839. Processing creation of tags could take longer then the time between the API requests. Adding the status code `422` to the retry configuration could solve this problem as it uses three attempts with additional time between the attempts.

fix(retry): also handle status code 422 #839

---

lib/definitions/errors.js
lib/glab.js
lib/publish.js
lib/verify.js
test/verify.test.js

Contributes to https://github.com/semantic-release/gitlab/issues/822

feat: raise error when GitLab CLI is required but not installed

---

lib/publish.js
test/publish.test.js

This should fix #823 while adding the file basename fallback for a label as the description in the README highlights.

fix(generix-package): add missing fallback for label #823
